SELECT DISTINCT  o.USER_ID, o.PRODUCT_ID
FROM ONLINE_SALE o, ONLINE_SALE ro

WHERE o.PRODUCT_ID = ro.PRODUCT_ID
AND o.USER_ID = ro.USER_ID
AND o.ONLINE_SALE_ID != ro.ONLINE_SALE_ID

ORDER BY o.USER_ID ASC, o.PRODUCT_ID DESC
;
