SELECT p.CATEGORY, p.PRICE AS MAX_PRICE, p.PRODUCT_NAME
FROM FOOD_PRODUCT p
WHERE (p.CATEGORY, p.PRICE) IN (
    SELECT p.CATEGORY, MAX(p.PRICE)
    FROM FOOD_PRODUCT p
    GROUP BY p.CATEGORY
    )
    AND p.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY p.PRICE DESC
;