SELECT  r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
WHERE (r.FOOD_TYPE, r.FAVORITES) IN (
    SELECT r.FOOD_TYPE, MAX(r.FAVORITES)
    FROM REST_INFO r
    GROUP BY r.FOOD_TYPE
    )
ORDER BY r.FOOD_TYPE DESC
;