SELECT c.CAR_ID, CASE WHEN c.CAR_ID IN 
    (SELECT c.CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
    WHERE '2022-10-16' BETWEEN c.START_DATE AND c.END_DATE) THEN '대여중'
    ELSE '대여 가능' END 'AVAILABILITY'
    
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
GROUP BY c.CAR_ID
ORDER BY c.CAR_ID desc;