-- SELECT b.WRITER_ID, COUNT(b.BOARD_ID) FROM USED_GOODS_BOARD b GROUP BY b.WRITER_ID ORDER BY b.WRITER_ID
SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) as '전체주소', REGEXP_REPLACE(u.TLNO, '([0-9]{3})([0-9]{4})([0-9]{4})', '$1-$2-$3') as '전화번호'
FROM (  SELECT b.WRITER_ID, COUNT(*) as CNT
        FROM USED_GOODS_BOARD b
        GROUP BY b.WRITER_ID
        HAVING COUNT(*) >=3) c
JOIN USED_GOODS_USER u ON u.USER_ID = c.WRITER_ID
ORDER BY u.USER_ID desc
;