SELECT h.HISTORY_ID, h.CAR_ID, h.START_DATE, h.END_DATE, CASE WHEN DATEDIFF(h.end_date,h.start_date) +1 >= 30 THEN '장기 대여' ELSE '단기 대여' END AS 'RENT_TYPE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE YEAR(h.START_DATE) = '2022' AND MONTH(h.START_DATE) = '9'
ORDER BY h.HISTORY_ID desc;
-- 나대지마