-- SELECT COUNT(*)
SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) as MONTH, u.GENDER, COUNT(DISTINCT o.USER_ID) AS USERS
FROM ONLINE_SALE o
LEFT JOIN USER_INFO u ON u.USER_ID = o.USER_ID
WHERE u.GENDER is not null
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
ORDER BY YEAR, MONTH, u.GENDER

-- WHERE MONTH(o.SALES_DATE) = 3
