SELECT m.MEMBER_ID, m.MEMBER_NAME,m.GENDER, DATE_FORMAT(m.DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE m
WHERE MONTH(m.DATE_OF_BIRTH) = '03' and
m.GENDER = 'W' and 
m.TLNO is not null
ORDER BY m.MEMBER_ID ASC
;