


SELECT U.USER_ID, U.NICKNAME, B.TOTAL_PRICE
FROM (
    SELECT B.WRITER_ID, B.STATUS, SUM(B.PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD B
    WHERE B.STATUS = 'DONE'
    GROUP BY B.WRITER_ID) B
JOIN USED_GOODS_USER U 
ON B.WRITER_ID = U.USER_ID
WHERE B.TOTAL_PRICE >= 700000
ORDER BY B.TOTAL_PRICE